<?php

namespace Tatum\model\response\ltc;


use Tatum\model\Model;

/**
 *
 * @export
 * @interface LtcTx
 */
class LtcTx extends Model {
    /**
     * Transaction hash.
* @var string
     * @memberof LtcTx
     */
    public $hash;
    /**
     * Witness hash in case of a SegWit transaction.
* @var string
     * @memberof LtcTx
     */
    public $witnessHash;
    /**
     * Fee paid for this transaction, in LTC.
* @var string
     * @memberof LtcTx
     */
    public $fee;
    /**
     *
* @var string
     * @memberof LtcTx
     */
    public $rate;
    /**
     *
* @var number
     * @memberof LtcTx
     */
    public $ps;
    /**
     * Height of the block this transaction belongs to.
* @var number
     * @memberof LtcTx
     */
    public $height;
    /**
     * Hash of the block this transaction belongs to.
* @var string
     * @memberof LtcTx
     */
    public $block;
    /**
     * Time of the transaction.
* @var number
     * @memberof LtcTx
     */
    public $ts;
    /**
     * Index of the transaction in the block.
* @var number
     * @memberof LtcTx
     */
    public $index;
    /**
     * Index of the transaction.
* @var number
     * @memberof LtcTx
     */
    public $version;
    /**
     *
* @var number
     * @memberof LtcTx
     */
    public $flag;
    /**
     *
* @var Array
<LtcTxInputs>
     * @memberof LtcTx
     */
public $inputs;
    /**
     *
    * @var Array
    <LtcTxOutputs>
     * @memberof LtcTx
     */
public $outputs;
    /**
     * Block this transaction was included in.
        * @var number
     * @memberof LtcTx
     */
    public $locktime;
}

/**
 *
 * @export
 * @interface LtcTxCoin
 */
class LtcTxCoin extends Model {
    /**
     *
        * @var number
     * @memberof LtcTxCoin
     */
    public $version;
    /**
     *
        * @var number
     * @memberof LtcTxCoin
     */
    public $height;
    /**
     *
        * @var string
     * @memberof LtcTxCoin
     */
    public $value;
    /**
     *
        * @var string
     * @memberof LtcTxCoin
     */
    public $script;
    /**
     * Sender address.
        * @var string
     * @memberof LtcTxCoin
     */
    public $address;
    /**
     * Coinbase transaction - miner fee.
        * @var boolean
     * @memberof LtcTxCoin
     */
public $coinbase;
}

/**
 *
 * @export
 * @interface LtcTxInputs
 */
class LtcTxInputs extends Model {
    /**
     *
        * @var LtcTxPrevout
     * @memberof LtcTxInputs
     */
public $prevout;
    /**
     * Data generated by a spender which is almost always used as variables to satisfy a pubkey script.
        * @var string
     * @memberof LtcTxInputs
     */
    public $script;
    /**
     * Transaction witness.
        * @var string
     * @memberof LtcTxInputs
     */
    public $witness;
    /**
     *
        * @var number
     * @memberof LtcTxInputs
     */
    public $sequence;
    /**
     *
        * @var LtcTxCoin
     * @memberof LtcTxInputs
     */
public $coin;
}

/**
 *
 * @export
 * @interface LtcTxOutputs
 */
class LtcTxOutputs extends Model {
    /**
     * Sent amount in LTC.
        * @var string
     * @memberof LtcTxOutputs
     */
    public $value;
    /**
     * Transaction script.
        * @var string
     * @memberof LtcTxOutputs
     */
    public $script;
    /**
     * Recipient address.
        * @var string
     * @memberof LtcTxOutputs
     */
    public $address;
}

/**
 *
 * @export
 * @interface LtcTxPrevout
 */
class LtcTxPrevout extends Model {
    /**
     * Transaction hash of the input.
        * @var string
     * @memberof LtcTxPrevout
     */
    public $hash;
    /**
     * Transaction index of the input.
        * @var number
     * @memberof LtcTxPrevout
     */
    public $index;
}