<?php

namespace Tatum\model\response\ltc;


use Tatum\model\Model;

/**
 *
 * @export
 * @interface LtcUTXO
 */
class LtcUTXO extends Model {
    /**
     * Version of the UTXO.
* @var number
     * @memberof LtcUTXO
     */
    public $version;
    /**
     *
* @var number
     * @memberof LtcUTXO
     */
    public $height;
    /**
     * Amount of UTXO in satoshis.
* @var string
     * @memberof LtcUTXO
     */
    public $value;
    /**
     * Data generated by a spender which is almost always used as variables to satisfy a pubkey script.
* @var string
     * @memberof LtcUTXO
     */
    public $script;
    /**
     * Address of the owner of the UTXO.
* @var string
     * @memberof LtcUTXO
     */
    public $address;
    /**
     * Coinbase transaction - miner fee.
* @var boolean
     * @memberof LtcUTXO
     */
public $coinbase;
    /**
     * Transaction hash.
* @var string
     * @memberof LtcUTXO
     */
    public $hash;
    /**
     * Transaction index of the output.
* @var number
     * @memberof LtcUTXO
     */
    public $index;
}